### ISSUE TITLE
is it still maintained? 

### ISSUE THREAD

**Issue by SammyHam** [FraserHamilton/dayjs-recur#7]
Hello Guys,

I'm looking for an alternative to moment JS, I'm switching to DayJS and used to work with moment-recur which is a great library.

I found your repo doing some research and love what you did! I would like to know do you plan to maintain this plug-in?
Thank you.

**Comment by FraserHamilton** [comment]
Apologises for the late reply I had notifications turned off. This project was put off while I was finishing university but the plan is to return to it and maintain it. I also plan to continue developing other utilities for dayjs. Is there any other plug-ins you would like to see?

**Comment by KoenBrouwer** [comment]
> Is there any other plug-ins you would like to see?

Not a plugin, but I'm currently using this quirk to have Typescript not get mad about missing type definitions. It would be great if you could add definitions for Typescript (.d.ts).

```typescript
declare module "dayjs" {
	interface Dayjs {
		recur: Function
	}
}
```

**Comment by KoenBrouwer** [comment]
> Is there any other plug-ins you would like to see?

@FraserHamilton Not a plugin, but I'm currently using this quirk to have Typescript not get mad about missing type definitions. It would be great if you could add definitions for Typescript (.d.ts).

```typescript
declare module "dayjs" {
	interface Dayjs {
		recur: Function
	}
}
```
